name: Deployment no servidor

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Obtiene el código
        uses: actions/checkout@v3
      - name: Deploy a producción
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          host: ${{ secrets.SSH_HOST }}
          script: "cd /var/www/app && chmod u+x server_deploy.sh && ./server_deploy.sh"
